#!/usr/bin/env -S npx tsx
/**
 * Seed D1 database with 5,000 synthetic customers and their transactions.
 *
 * Usage:
 *   npx tsx scripts/seed-d1.ts > seed.sql
 *   npx wrangler d1 execute veil-rfm-db --file seed.sql --remote
 */

import { generateSynthetic } from "../packages/core/src/generate"
import { getRFMData, rfmCompute, rfmSegmentation } from "../packages/core/src/rfm"

const TOTAL_CUSTOMERS = 5000
const SEED = 20260603
const TXN_BATCH = 50

// Generate all 5,000 customers in one go to avoid ID collisions
const { transactions } = generateSynthetic({ customers: TOTAL_CUSTOMERS, seed: SEED })
const rfmData = getRFMData(transactions)
const rfmScore = rfmCompute(rfmData)
const rfmSegment = rfmSegmentation(rfmScore)

const allCustomers: string[] = []
const allTxns: string[] = []

// Compute customer data
for (let i = 0; i < rfmSegment.length; i++) {
  const seg = rfmSegment[i]
  const data = rfmData.find((d) => d.CustomerID === seg.CustomerID)!
  const score = rfmScore.find((s) => s.CustomerID === seg.CustomerID)!
  const avgOrder = data.NoOfTxn > 0 ? Math.round(data.TotalSpending / data.NoOfTxn) : 0

  allCustomers.push(
    `('${data.CustomerID}','${seg.Segment}',${score.RecencyScore},${score.FrequencyScore},${score.MonetaryScore},${data.DaySinceLastTxn},${data.NoOfTxn},${data.TotalSpending},${avgOrder})`,
  )
}

// Batch transactions
for (let i = 0; i < transactions.length; i += TXN_BATCH) {
  const batch = transactions.slice(i, i + TXN_BATCH)
  const values = batch
    .map(
      (t) =>
        `('${t.MemberID}','${t.OrderID}','${t.Timestamp}',${t.NetPrice},${t.Quantity},'${t.ProductID}','${t.ProductName.replace(/'/g, "''")}','${t.Category}','${t.Gender ?? ""}')`,
    )
    .join(",")
  allTxns.push(`INSERT INTO transactions (MemberID,OrderID,Timestamp,NetPrice,Quantity,ProductID,ProductName,Category,Gender) VALUES ${values};`)
}

// Output SQL
console.log("-- Seed D1: 5,000 customers + transactions (single seed)")
console.log(`-- Seed: ${SEED}, Customers: ${TOTAL_CUSTOMERS}`)
console.log("-- Generated by scripts/seed-d1.ts")
console.log()

// Insert customers in batches of 200
let count = 0
for (let i = 0; i < allCustomers.length; i += 200) {
  const batch = allCustomers.slice(i, i + 200).join(",")
  console.log(`INSERT OR REPLACE INTO customers (CustomerID,Segment,RecencyScore,FrequencyScore,MonetaryScore,DaySinceLastTxn,NoOfTxn,TotalSpending,AvgOrderValue) VALUES ${batch};`)
  count++
}
console.error(`  Customers: ${allCustomers.length} rows in ${count} batches`)

// Transaction batches (already batched)
console.error(`  Transactions: ${allTxns.length} batches`)
for (const txn of allTxns) {
  console.log(txn)
}
